# Sistema de Ecommerce De Krowdi
version: '3.3'

services:
  db:
    image: "postgres"
    container_name: psql_atlas_puntos
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbprouatlas
      POSTGRES_PASSWORD: F2rYvlZYfj
      POSTGRES_DB: dbpro_atlas_puntos
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      atlas-puntos:
        ipv4_address: 172.16.1.30

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin_atlas_puntos
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      atlas-puntos:
        ipv4_address: 172.16.1.20
    environment:
      PGADMIN_DEFAULT_EMAIL: yahyrparedesarteaga@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 73884071
    volumes:
      - ./pgadmin:/root/.pgadmin

# Descomentar y ejecutar si quieres probar el back para dev no lo uses
#  backend:
#    image: "node:10"
#    container_name: back_atlas_puntos
#    build:
#      context: ./backend
#    restart: on-failure
#    ports:
#      - 3000:3000
#    volumes:
#      - ./backend:/home/backend
#    working_dir: /home/backend
#    depends_on:
#      - db
#      - pgadmin
#    networks:
#      atlas-puntos:
#        ipv4_address: 172.16.1.10
#    command: bash -c "npm install && npm run dev"

networks:
  atlas-puntos:
    # driver: bridge
    external: true
      # ipam:
      # config:
    # - subnet: 172.16.1.0/24
    # gateway: 192.168.100.1

#  docker network create --gateway 172.16.1.1 --subnet 172.16.1.0/24 atlas-puntos


  mongo-express:
    image: "mongo-express"
    container_name: mongoadmin_krowdy
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      krowdy:
        ipv4_address: 172.16.2.101